In [1]:
import numpy as np, cv2

In [2]:
def SVM_create(type, max_iter, epsilon):
    svm = cv2.ml.SVM_create()                           # SVM 객체 선언
    # SVM 파라미터 지정
    svm.setType(cv2.ml.SVM_C_SVC)             # C-Support Vector Classification
    svm.setKernel(cv2.ml.SVM_LINEAR)                    # 선형 SVM
    svm.setGamma(1)                                     # 커널 함수의 감마 값
    svm.setC(1)                                         # 최적화를 위한 C 파라미터
    svm.setTermCriteria((type, max_iter, epsilon))      # 학습 반복 조건 지정
    return svm

In [16]:
nsample = 140
trainData = [cv2.imread("images/plate/%03d.png" %i, 0) for i in range(70,140)]

In [17]:
trainData

[array([[ 66,  60,  38, ..., 121, 172, 219],
        [ 72, 141,  66, ..., 210, 102, 167],
        [ 72,  88,  76, ..., 111, 222, 250],
        ...,
        [162, 131,  52, ...,   6,   9,   4],
        [222, 192,  72, ...,  45,  27,  18],
        [141,  72,  69, ...,  76,  47,  41]], dtype=uint8),
 array([[ 46,  46,  45, ..., 246, 244, 243],
        [ 45,  44,  41, ..., 247, 245, 244],
        [ 43,  42,  38, ..., 249, 248, 247],
        ...,
        [ 85,  85,  83, ..., 160, 154, 153],
        [ 85,  83,  77, ...,  97,  94,  92],
        [ 80,  77,  70, ...,  44,  44,  44]], dtype=uint8),
 array([[170, 170, 170, ..., 223, 226, 226],
        [122, 122, 122, ..., 209, 213, 213],
        [ 52,  52,  52, ..., 149, 149, 149],
        ...,
        [199, 199, 199, ..., 254, 255, 255],
        [206, 206, 206, ..., 255, 255, 255],
        [206, 206, 206, ..., 255, 255, 255]], dtype=uint8),
 array([[ 21,  21,  19, ...,  79,  45,  27],
        [152, 135, 120, ...,  36,  27,  24],
        [252, 25

In [18]:
trainData = np.reshape( trainData, (nsample, -1)).astype("float32")

In [19]:
labels = np.zeros((nsample,1), np.int32)
labels[:70] = 1

In [20]:
print("SVM 객체 생성")
svm = SVM_create(cv2.TERM_CRITERIA_MAX_ITER, 1000, 1e-6)   # SVM 객체 생성
svm.train(trainData, cv2.ml.ROW_SAMPLE, labels)             # 학습 수행
svm.save("SVMtrain.xml")                             # 학습된 데이터 저장
print("SVM 객체 저장 완료")

SVM 객체 생성
SVM 객체 저장 완료
