In [1]:
import numpy as np, cv2, math
import scipy.fftpack as sf

In [2]:
def cos(n,k,N):
    return math.cos((n + 1/2) * math.pi * k / N)

In [3]:
def C(k, N):
    return math.sqrt(1/N) if k==0 else math.sqrt(2/N)

In [4]:
def dct(g):
    N = len(g)
    f = [C(k, N) * sum(g[n] * cos(n, k, N ) for n in range(N)) for k in range(N)]
    return np.array(f, np.float32)

In [5]:
def idct(f):
    N = len(f)
    g = [sum(C(k, N) * f[k] * cos(n, k, N) for k in range(N)) for n in range(N)]
    return np.array(g)

In [6]:
def dct2(image):
    tmp = [dct(row) for row in image]
    dst = [dct(row) for row in np.transpose(tmp)]
    return np.transpose(dst)                   # 전치 환원 후 반환

In [7]:
def idct2(image):
    tmp = [idct(row) for row in image]
    dst = [idct(row) for row in np.transpose(tmp)]
    return np.transpose(dst)                   # 전치 환원 후 반환

In [8]:
def scipy_dct2(a):
    tmp = sf.dct(a, axis=0, norm='ortho' )
    return sf.dct(tmp, axis=1, norm='ortho' )

In [9]:
def scipy_idct2(a):
    tmp = sf.idct(a, axis=0, norm='ortho')
    return sf.idct(tmp, axis=1 , norm='ortho')

In [10]:
block = np.zeros((8,8), np.uint8)
cv2.randn(block, 128, 50)

array([[128, 136,  93, 107, 190, 114,  96, 143],
       [154,  71, 166, 126, 193,  30,  33, 101],
       [ 91, 223, 142,  59, 205,  89,   4,  51],
       [ 60, 125, 196, 168, 115, 102, 220, 146],
       [193,  96,  85, 182, 130, 114, 120, 110],
       [180, 152, 123, 179,  91,  98, 117, 186],
       [ 29, 163, 117, 133, 141,  86, 160, 120],
       [211, 114,  88, 163, 158, 162, 104,  99]], dtype=uint8)

In [11]:
dct1 = dct2(block)
dct2 = scipy_dct2(block)
dct3 = sf.dctn(block, shape=block.shape, norm='ortho')			# 2차원 dct 수행 다른 방식
dct4 = cv2.dct(block.astype("float32"))

In [12]:
idct1 = idct2(dct1)
idct2 = scipy_idct2(dct2)
idct3 = sf.idctn(dct3, shape=dct2.shape, norm='ortho')			# 2차원 dct 수행 다른 방식
idct4 = cv2.dct(dct4, flags=cv2.DCT_INVERSE)

In [13]:
print('block=\n', block)
print('dct1(저자구현 함수)=\n', dct1)
print('dct2(scipy 모듈 함수1)=\n', dct2)
print('dct3(scipy 모듈 함수2)=\n', dct3)
print('dct4(OpenCV 함수)=\n', dct4)
print()
print('idct1(저자구현 함수)=\n', cv2.convertScaleAbs(idct1))
print('idct2(scipy 모듈 함수1)=\n', cv2.convertScaleAbs(idct2))
print('idct3(scipy 모듈 함수2)=\n', cv2.convertScaleAbs(idct3))
print('idct4(OpenCV 함수)=\n', cv2.convertScaleAbs(idct4))

block=
 [[128 136  93 107 190 114  96 143]
 [154  71 166 126 193  30  33 101]
 [ 91 223 142  59 205  89   4  51]
 [ 60 125 196 168 115 102 220 146]
 [193  96  85 182 130 114 120 110]
 [180 152 123 179  91  98 117 186]
 [ 29 163 117 133 141  86 160 120]
 [211 114  88 163 158 162 104  99]]
dct1(저자구현 함수)=
 [[1010.125       66.28257    -46.4755     -21.431795    75.375
   -38.51036    -43.933865    30.88792  ]
 [ -49.188576    39.439724   -36.440662   -16.729065    17.86372
   -84.11798     23.710556    81.19413  ]
 [ -20.443415     7.045197   -10.812631    62.11756     45.385826
   -51.337383    14.928116    12.200523 ]
 [  24.471926   -48.239067    64.25619    -17.18532     51.097008
    49.593323    -6.691223   -43.100742 ]
 [  56.87501    -58.001377    14.010731    58.923492     9.125002
    86.76855      8.673561   -29.032633 ]
 [   9.9247     -89.663605   -14.28731    -72.784615  -127.56446
   -43.465958   -74.75635      4.8181767]
 [  23.486116    57.468174    37.928116    51.74977 