# Numpy
- Numerical Python

- 강력한 N 차원 배열 객체.list 보다 빠르다
- 정교한 브로드캐스팅 기능. 반복문을 쓰지 않음
- 유용한 선형 대수학, 푸리에 변환 및 난수 기능
- C/C ++ 및 포트란 코드 통합 도구

Numpy는 python코드가 아니라 C코드로 작성되어있다.

 메모리 저장구조가 다르다

## 임포트하기

In [5]:
import numpy as np

In [154]:
np.sum([1,2,3,4])
sum([1,2,3,4])

10

이건 오류
var([1,2,3,4])

## 함수 이름을 바로 쓰고 싶을 때

In [155]:
from numpy import var
np.var([1,2,3,4])
var([1,2,3,4])

1.25

## Array 만들기

- 각 차원을 축(axis)라고 합니다.
- 축의 개수는 차원의 개수인데 rank 라고도 합니다.
- 배열의 차원을 shape라고 하고 tuple로 표시합니다.
- shape안의 숫자는 각 차원에 있는 원소의 개수입니다.
- 전체 원소의 개수는 size라고 합니다.

In [161]:
# 입력값으로 list가 들어간다
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [162]:
a = np.array([0,1.0,2,3])
a

array([0., 1., 2., 3.])

In [163]:
# 리스트를 array로 바꾸기
a = [0,1,2,3]
np.array(a)

array([0, 1, 2, 3])

In [164]:
a = np.array([0,1,2,3])

In [165]:
a.dtype

dtype('int32')

In [169]:
# 차원의 갯수
a.ndim

1

In [171]:
# 해당 차원의 원소의 갯수 
a.shape

(4,)

In [173]:
# 원소의 갯수
a.size 

4

In [174]:
# 3/4 =8bytes = 64bit

In [178]:
a = np.array([0,1,2,3])
a.dtype

dtype('int32')

In [179]:
a = np.array([0,1,2.2,3])
a.dtype

dtype('float64')

In [185]:
# python내의 객체라 ''필요 없음
np.array([0,1,2,3], float)

array([0., 1., 2., 3.])

In [186]:
np.array([0,1,2.2,3], int)

array([0, 1, 2, 3])

In [188]:
# Numpy내의 객체라 '' 필요함
np.array([0,1,2,3], 'int8')

array([0, 1, 2, 3], dtype=int8)

In [189]:
np.array([0,1,2,3], dtype = 'int16')

array([0, 1, 2, 3], dtype=int16)

In [190]:
np.array([0,1,2,3], 'float32')

array([0., 1., 2., 3.], dtype=float32)

In [191]:
np.array([0,1,2,3], dtype = 'float64')

array([0., 1., 2., 3.])

## 2차원, 3차원 배열 만들기

In [192]:
# np.array()함수를 써서 만들기
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[3,4],[5,6]])

In [193]:
# 2x2x2 3차원 배열을 만들어 봅시다

np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [200]:
# arange란?
for i in range(3):
    print(i)

0
1
2


In [201]:
list(range(3))

[0, 1, 2]

In [202]:
for i in np.arange(3):
    print(i)

0
1
2


In [198]:
# arange()와 reshape()를 써서 만들기
np.arange(3) # array로 출력
a = np.arange(4)
a.shape

(4,)

In [203]:
a = np.arange(8)
a.shape
a.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [205]:
# .를 이용하여 한줄로 쓸수있다
np.arange(8).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [206]:
# 10 부터 21 까지의 숫자로 3행 4열 짜리를 만들어 주세요

np.arange(10,22).reshape( (3,4) )

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [210]:
# arange를 쓰면 데이터 타입도 정할수 있습니다.
np.arange(6, dtype = np.float32).reshape(2, 3)

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

In [211]:
# reshape(z,y,x)
np.arange(8).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [213]:
# 3차원 배열 만들기
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [214]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [215]:
np.arange(24).reshape(3,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [216]:
np.arange(24).reshape(4,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

shape( axis = z, axis = y "행", axis = x "열" )

## 배열의 연산
- 리스트의 연산과 비슷하지만,약간 다르다
- numpy함수를 쓰는것 보다 객체.함수()가 편리하다
- Numpy의 연산은 원소들 끼리 이루어진다. element wise
- array의 형태(shape)가 안 맞으면, 자동으로 맞추어 주기도 한다. broadcasting

In [218]:
a = [1,2,3,4]
b = [5,6,7,8]

np.array(a) + np.array(b) # element wise

array([ 6,  8, 10, 12])

In [219]:
# row wise, colum wise

a = np.array(a)
b = np.array(b)

In [220]:
a*3

array([ 3,  6,  9, 12])

In [238]:
a + 1

array([2, 3, 4, 5])

In [221]:
type(a)

numpy.ndarray

In [222]:
a + b

array([ 6,  8, 10, 12])

In [223]:
np.add(a, b)

array([ 6,  8, 10, 12])

In [225]:
# 차원의 갯수가 달라도 더해진다
c = np.array([10])

a + c

array([11, 12, 13, 14])

In [226]:
arr3 = np.array([[[1,2],
                  [3,4]],
                 
                 [[5,6],
                  [7,8]]])

In [227]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)

In [228]:
arr1 + arr2

array([[ 6,  8],
       [10, 12]])

In [234]:
np.add(arr1,arr2)

array([[ 6,  8],
       [10, 12]])

In [229]:
arr1 - arr2

array([[-4, -4],
       [-4, -4]])

In [235]:
np.subtract(arr1,arr2)

array([[-4, -4],
       [-4, -4]])

In [231]:
# 같은 인덱스끼리 곱해주는거라 행렬의 곱과는 다르다
arr1 * arr2

array([[ 5, 12],
       [21, 32]])

In [236]:
np.multiply(arr1,arr2)

array([[ 5, 12],
       [21, 32]])

In [232]:
arr1 / arr2

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [237]:
np.divide(arr1,arr2)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [233]:
arr1 @ arr2 # 행렬의 곱셈

array([[19, 22],
       [43, 50]])

In [60]:
np.dot(arr1,arr2)

array([[19, 22],
       [43, 50]])

## Numpy 내장함수를 이용하여 array 만들기

In [241]:
# arange
np.arange(36).reshape(3, 4, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [242]:
np.arange(1, 9 ,2)

array([1, 3, 5, 7])

In [67]:
a = np.array(9, dtype= np.float32)
a

array(9., dtype=float32)

In [245]:
# linspace ( start, stop, number of element
np.linspace(0, 1, 5, endpoint= False)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [246]:
# ones ( dtype, oder)
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [249]:
# zeros( shape [ dtype, oder] )
b = np.zeros((3, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [251]:
 b[2,0] = 3 # sparse matrix
 b 

array([[0., 0., 0.],
       [0., 0., 0.],
       [3., 0., 0.]])

In [252]:
# diagonal은 대각선
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [259]:
np.diag([0,4,8])

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

In [76]:
c = np.arange(9).reshape(3,3)
np.diag(c)

array([0, 4, 8])

In [257]:
np.ones((3,3),int)*8

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [258]:
# full ( shape, fill_value )
np.full((3,3),8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [260]:
# np.identity()  단위 행, 정사각행렬이 정해져 있다

np.diag([1,1])

array([[1, 0],
       [0, 1]])

In [261]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [262]:
# eye : eye(4)와 np.identity(4)는 같다
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [263]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [264]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [265]:
# tile ( shape , 반복 )
np.tile([1,2,3], 2)

array([1, 2, 3, 1, 2, 3])

In [266]:
np.tile(np.array([1,2,3]), 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [267]:
np.tile([1,2,3], (3, 2)) # 2번씩 3행

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [268]:
# empty null에 해당하는 주소값, 초기화 안함
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [269]:
### like  형태와 데이터 타입은 유지

a = np.arange(6).reshape(2,3)

In [270]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

In [271]:
b = np.arange(3, dtype = np.float16)

In [272]:
np.zeros_like(b)

array([0., 0., 0.], dtype=float16)

In [273]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

In [274]:
np.ones_like(b)

array([1., 1., 1.], dtype=float16)

## copy와 view
- 기본 배열로부터 새로운 배열을 생성하기 위해서는 copy함수로 명시적으로 사용해야 함
- copy 함수로 복사한 배열은 원본 배열과 완전히 다른 새로운 객체입니다.
- slice,indexing은 새로운 객체가 아닌 기존 배열의 뷰(View)입니다.
- 반환한 배열의 값을 변경하면 원본 배열이 변경된다.

In [276]:
a = np.arange(1,6)
b = a.copy()

b[3] = 0
b

array([1, 2, 3, 0, 5])

In [277]:
# a를 카피한 b값이 바뀌어도 a값은 바뀌지 않는다

a

array([1, 2, 3, 4, 5])

In [278]:
c = a
c[3] = 0

In [280]:
# a의 주소값을 복사한 c의 값이 바뀌니 a의 값도 바뀐다
a

array([1, 2, 3, 0, 5])

In [281]:
a = np.arange(1,6)


b = a[ 2:4]
b[0] = 0
b

array([0, 4])

In [104]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [105]:
np.linspace(0, 1, 6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [106]:
np.ones((3,3),int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## 배열의 결합

- hstack
- vstack
- dstack
- concatenate

In [284]:
### stack

a = np.arange(5)
a*10

array([ 0, 10, 20, 30, 40])

In [285]:
# vstack 행 결합
np.vstack([a,a * 10])

array([[ 0,  1,  2,  3,  4],
       [ 0, 10, 20, 30, 40]])

In [286]:
np.vstack([a,a * 10, a * 20, a -10])

array([[  0,   1,   2,   3,   4],
       [  0,  10,  20,  30,  40],
       [  0,  20,  40,  60,  80],
       [-10,  -9,  -8,  -7,  -6]])

In [287]:
np.vstack([a,a * 10])

array([[ 0,  1,  2,  3,  4],
       [ 0, 10, 20, 30, 40]])

In [111]:
np.vstack([a,a * 10])

array([[ 0,  1,  2,  3,  4],
       [ 0, 10, 20, 30, 40]])

In [288]:
# hstack 열 결합
np.hstack([a,a * 10])

array([ 0,  1,  2,  3,  4,  0, 10, 20, 30, 40])

In [289]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [290]:
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6]])

In [291]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6])

In [292]:
# dstack 행 열 반전 결합
np.dstack([a,b])

array([[[1, 4],
        [2, 5],
        [3, 6]]])

## 배열의 분리
- spliting
- 수평분리 hsplit
- 수직분리 vsplit

In [298]:
a = np.arange(1, 25).reshape((4,6))

In [300]:
# vsplit은 수직으로 나눈다
np.vsplit(a,2)

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])]

In [301]:
type(a)

numpy.ndarray

In [302]:
np.array(np.vsplit(a,2)).shape

(2, 2, 6)

np.vsplit(a,3)

TypeError Traceback

In [303]:
# hsplit 수평으로 나눈다
np.hsplit(a,3)

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22]]),
 array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24]])]

In [304]:
np.hsplit(a,2)

[array([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15],
        [19, 20, 21]]),
 array([[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18],
        [22, 23, 24]])]

np.hsplit(a,4)

ValueError: array split does not result in an equal division

## Numpy의 shape 변경 함수

In [309]:
# reshape( axis z, axos y, axis x )
np.arange(24).reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

np.arange(24).reshape(3, )

ValueError: cannot reshape array of size 24 into shape (3,)

In [311]:
np.arange(24).reshape(3,-1) # -1은 자동으로 맞추어 주라는 뜻

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [312]:
np.arange(24).reshape(4,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [313]:
np.arange(24).reshape(-1,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [317]:
# flatten
a = np.arange(24).reshape(3,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [318]:
a.flatten().shape

(24,)

In [319]:
# ravel

b = a.ravel()
b[0] = 100
b

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [134]:
a # 같이 바뀌었다 view

array([[100,   1,   2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20,  21,  22,  23]])

In [320]:
# transpose 행렬의 곱셈을 가능하게 해줍니다.
a = np.arange(24).reshape(3,8)
a @ a.T

array([[ 140,  364,  588],
       [ 364, 1100, 1836],
       [ 588, 1836, 3084]])

## 배열의 비교
- 같다(==)
- 크다,작다
- 배열 전체를 하나로 비교(np.array_equal)

In [321]:
a = np.array([1,2,3,4])
b = np.array([3,4,5,6])

a == b

array([False, False, False, False])

In [322]:
a > b

array([False, False, False, False])

In [323]:
np.array_equal(a, b)

False

## 정렬하기
- numpy.sort()와 객체.sort()는 다르다
- 1차원 배열의 정렬, 역순으로 정렬
- 2차원 배열의 정렬과 축기준으로 정렬하기

In [336]:
A = np.array([2,1,4,3])
B = np.sort(A)
B

array([1, 2, 3, 4])

In [337]:
A

array([2, 1, 4, 3])

In [340]:
A.sort() # A를 정렬하고 바로 저장
A

array([1, 2, 3, 4])

In [341]:
a= [2,1,4,3]
b = np.sort(a)
a

[2, 1, 4, 3]

In [342]:
sorted(a) # sorted : python의 내장함수
a.sort()
a

[1, 2, 3, 4]

In [343]:
a = np.array([4,2,6,5,1,3,0])
a[ : :2]

array([4, 6, 1, 0])

In [346]:
a[::-1]

array([0, 3, 1, 5, 6, 2, 4])

In [345]:
# 역순으로 정렬하기
np.sort(a)[::-1]

array([6, 5, 4, 3, 2, 1, 0])

In [147]:
x = np.array([[2,1,6],
              [0,7,4],
              [5,3,2]])

In [347]:
np.sort(x)

array([[1, 2, 6],
       [0, 4, 7],
       [2, 3, 5]])

In [348]:
np.sort(x, axis = 0)

array([[0, 1, 2],
       [2, 3, 4],
       [5, 7, 6]])

In [349]:
np.sort(x, axis = 1)

array([[1, 2, 6],
       [0, 4, 7],
       [2, 3, 5]])

## indexing

In [67]:
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [53]:
a.ndim

1

In [54]:
a.size

4

In [55]:
a.nbytes

16

In [56]:
a.dtype

dtype('int32')

In [57]:
a[0] = 10
a[0]

10

In [66]:
# 2d indexing
a = np.array([[0,1,2,3],[10,11,12,13]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [59]:
a.ndim

2

In [60]:
a.shape

(2, 4)

In [61]:
a.size

8

In [62]:
a[1,3]
a[1,3] = -1

In [63]:
a[1]

array([10, 11, 12, -1])

In [64]:
a[1,]

array([10, 11, 12, -1])

In [65]:
#a[,1] << 빈칸을 인식을 못함/ 대신:로 빈칸의미
a[:,1]

array([ 1, 11])

## slicing

In [73]:
### slicing은 원본 View

a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [74]:
a[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [75]:
a[4::]

array([[20, 21, 22, 23, 24]])

In [4]:
a[:,1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [76]:
a[1::2,0:3:2] # 1행부터 2단위 전부
              # 0열부터 2단위 3열까지

array([[ 5,  7],
       [15, 17]])

## Fancy Indexing.position

정수배열 indexer를 사용해서 indexing하는 방법

In [82]:
a = np.arange(0, 80, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [83]:
a[[0,1]]

array([ 0, 10])

In [7]:
a[[0,1,3,5]]

array([ 0, 10, 30, 50])

In [8]:
indices = [0,1,3,5]

a[indices]

array([ 0, 10, 30, 50])

In [84]:
a[indices] = 9
a

array([ 9,  9, 20,  9, 40,  9, 60, 70])

In [85]:
a= np.arange(36).reshape(6,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [86]:
a[1]

array([ 6,  7,  8,  9, 10, 11])

In [11]:
a[2]

array([12, 13, 14, 15, 16, 17])

In [87]:
a[[1,2]]

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [88]:
a[indices]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23],
       [30, 31, 32, 33, 34, 35]])

In [14]:
a[indices, indices]

array([ 0,  7, 21, 35])

In [15]:
a[[0,1,3,5],[0,1,3,5]]

array([ 0,  7, 21, 35])

In [16]:
a[[0,1,2,2],[1,2,0,3]]

array([ 1,  8, 12, 15])

In [17]:
a = np.arange(0,80,10)

a[a>40]

array([50, 60, 70])

In [18]:
a[(a>40)|(a<30)]

array([ 0, 10, 20, 50, 60, 70])

In [19]:
mask = a>40
a[mask]

array([50, 60, 70])

In [22]:
a = np.arange(25).reshape(5,5)

mask1 = np.array((1,1,1,1,0), dtype = bool)
mask2 = np.array((0,1,1,1,1), dtype = bool)

a[mask1,mask2]

array([ 1,  7, 13, 19])

## broad casting
- 차원(dimension)이 다른 두 배열의 연산에서
- 낮은 차원의 배열이 차원을 맞추어 주도록 변화한다
- 데이터의 복사를 하지 않으므로 빠르다

In [90]:
a = np.array([1,2,3])
a + 1

array([2, 3, 4])

In [91]:
a = np.ones((3,5))
b = np.ones((5, ))
a + b

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [94]:
# 배열 수학

a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
sum(a)

array([5, 7, 9])

In [96]:
np.sum(a)

21

In [97]:
np.sum(a, axis = 0)

array([5, 7, 9])

In [98]:
np.sum(a, axis = 1)

array([ 6, 15])

In [99]:
np.min(a)

1

In [100]:
np.min(a, axis = 0)

array([1, 2, 3])

In [101]:
np.min(a, axis = 1)

array([1, 4])

In [102]:
b = np.array([[4,5,6],[1,2,3]])
np.minimum(a,b)

array([[1, 2, 3],
       [1, 2, 3]])

In [103]:
np.argmin(a) # 결과 값은 인덱스 번호 

0

In [104]:
np.argmax(a)  

5

In [105]:
c = np.array([2,1,3,5,4,2])
np.max(c)

5

In [106]:
np.argmax(c) # index 위치

3

In [107]:
a > 4

array([[False, False, False],
       [False,  True,  True]])

In [108]:
a[a>4]

array([5, 6])

In [109]:
np.where( a> 4)

(array([1, 1], dtype=int64), array([1, 2], dtype=int64))

In [110]:
np.where( a> 4, "H", "h")

array([['h', 'h', 'h'],
       ['h', 'H', 'H']], dtype='<U1')

In [111]:
a = np.arange(-15,15).reshape(5,6) ** 2

In [1]:
# list 두개를 더해서 새로 리스트를 만들자

li1= [1,2,3,4]
li2= [1,2,3,4]
li3 = []

In [2]:
for i in range(len(li1)):
    li3.append(li1[i]+li2[i])

print(li3)

[2, 4, 6, 8]


In [11]:
import timeit

def test():
    li1 = list(range(1,4000))
    li2 = list(range(1,4000))
    li3 = []
    for i in range(len(li1)):
        li3.append(li1[i]+li2[i])
    print(li3)

def test1():    
    a4= np.arange(1,4000)
    a5= np.arange(1,4000)
    a6 = a4 + a5
    print(a6)

In [12]:
timeit.timeit(test, number = 10)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 362, 364, 366, 368, 370, 372, 374, 376, 378, 380, 382, 384, 386, 388, 390, 392, 394, 396, 398, 400, 402, 404, 406, 408, 410, 412, 414, 416, 418, 420, 42

0.005705700000021352

In [13]:
timeit.timeit(test1, number = 10)

[   2    4    6 ... 7994 7996 7998]
[   2    4    6 ... 7994 7996 7998]
[   2    4    6 ... 7994 7996 7998]
[   2    4    6 ... 7994 7996 7998]
[   2    4    6 ... 7994 7996 7998]
[   2    4    6 ... 7994 7996 7998]
[   2    4    6 ... 7994 7996 7998]
[   2    4    6 ... 7994 7996 7998]
[   2    4    6 ... 7994 7996 7998]
[   2    4    6 ... 7994 7996 7998]


0.001360699999992221