In [16]:
import torch

In [6]:
torch.manual_seed(1)

In [7]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [8]:
print(x_train)

tensor([[1.],
        [2.],
        [3.]])


In [10]:
print(x_train.shape)

torch.Size([3, 1])


In [18]:
w = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

## HYPOTHESIS

In [21]:
hypothesis = x_train * w + b
print(hypothesis)

tensor([[2.0372],
        [4.0080],
        [5.9788]], grad_fn=<AddBackward0>)


## LOSS

In [23]:
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(0.0006, grad_fn=<MeanBackward0>)


## GRADIENT DESCENT

In [25]:
optimizer = torch.optim.SGD([w, b], lr=0.01)
optimizer.zero_grad()
cost.backward()
optimizer.step()

In [31]:
print(w)
print(b)
print(cost)

tensor([1.9998], requires_grad=True)
tensor([0.0005], requires_grad=True)
tensor(4.1998e-08, grad_fn=<MeanBackward0>)


In [29]:
nb_epochs = 1000
for epoch in range(1, nb_epochs + 1):
    hypothesis = x_train * w + b
    cost = torch.mean((hypothesis - y_train) ** 2)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

In [3]:
import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

C:\Anaconda3\envs\py39tf2\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [5]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

In [6]:
W = 0

In [7]:
gradient = torch.sum((W * x_train - y_train) * x_train)
print(gradient)

tensor(-14.)


In [8]:
lr = 0.1
W -= lr * gradient
print(W)

tensor(1.4000)


In [9]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])
# 모델 초기화
W = torch.zeros(1)
# learning rate 설정
lr = 0.1

nb_epochs = 10
for epoch in range(nb_epochs + 1):
    
    # H(x) 계산
    hypothesis = x_train * W
    
    # cost gradient 계산
    cost = torch.mean((hypothesis - y_train) ** 2)
    gradient = torch.sum((W * x_train - y_train) * x_train)

    print('Epoch {:4d}/{} W: {:.3f}, Cost: {:.6f}'.format(
        epoch, nb_epochs, W.item(), cost.item()
    ))

    # cost gradient로 H(x) 개선
    W -= lr * gradient

Epoch    0/10 W: 0.000, Cost: 4.666667
Epoch    1/10 W: 1.400, Cost: 0.746666
Epoch    2/10 W: 0.840, Cost: 0.119467
Epoch    3/10 W: 1.064, Cost: 0.019115
Epoch    4/10 W: 0.974, Cost: 0.003058
Epoch    5/10 W: 1.010, Cost: 0.000489
Epoch    6/10 W: 0.996, Cost: 0.000078
Epoch    7/10 W: 1.002, Cost: 0.000013
Epoch    8/10 W: 0.999, Cost: 0.000002
Epoch    9/10 W: 1.000, Cost: 0.000000
Epoch   10/10 W: 1.000, Cost: 0.000000
